import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

import TopNavBar from "@/Components/Navbar/TopNavBar";
import BottomNav from "@/Components/Navbar/BottomNav";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full flex justify-center items-center mx-auto bg-gray-100 `}
      >
        <div className="relative sm:max-w-[375px] sm:h-[667px] w-full h-full sm:border-6 sm:border-gray-950  sm:rounded-2xl sm:shadow-2xl flex flex-col overflow-hidden my-[50px]">
          <div className="fixed sm:absolute top-0  w-full  z-50">
            <TopNavBar />
          </div>

          <div className="flex-1 overflow-y-auto no-scrollbar mt-15 mb-8  px-2 w-full h-full sm:mt-20  ">
            {children}
          </div>
          <div className="fixed sm:absolute bottom-0 bg-white w-full z-500">
            <BottomNav />

          </div>
        </div>

      </body>
    </html>
  );
}
